// export enum CompletionItemKind {
//   Text = 0,
//   Method = 1,
//   Function = 2,
//   Constructor = 3,
//   Field = 4,
//   Variable = 5,
//   Class = 6,
//   Interface = 7,
//   Module = 8,
//   Property = 9,
//   Unit = 10,
//   Value = 11,
//   Enum = 12,
//   Keyword = 13,
//   Snippet = 14,
//   Color = 15,
//   Reference = 17,
//   File = 16,
//   Folder = 18,
//   EnumMember = 19,
//   Constant = 20,
//   Struct = 21,
//   Event = 22,
//   Operator = 23,
//   TypeParameter = 24,
//   User = 25,
//   Issue = 26,
// }
const fs = require('fs')

const CompletionItemKind = {
  Text: 0,
  Method: 1,
  Function: 2,
  Constructor: 3,
  Field: 4,
  Variable: 5,
  Class: 6,
  Interface: 7,
  Module: 8,
  Property: 9,
  Unit: 10,
  Value: 11,
  Enum: 12,
  Keyword: 13,
  Snippet: 14,
  Color: 15,
  Reference: 17,
  File: 16,
  Folder: 18,
  EnumMember: 19,
  Constant: 20,
  Struct: 21,
  Event: 22,
  Operator: 23,
  TypeParameter: 24,
  User: 25,
  Issue: 26,
}

const { Function, Value, Constant, Keyword, Property } = CompletionItemKind

const batKws = [
  'call',
  'do',
  'else',
  'endlocal',
  'exit',
  'for',
  'goto',
  'if',
  'in',
  'pause',
  'setlocal',
]
const batCmds = [
  'break',
  'cd',
  'cls',
  'color',
  'copy',
  'date',
  'del',
  'dir',
  'echo',
  'md',
  'mklink',
  'move',
  'popd',
  'prompt',
  'pushd',
  'rd',
  'ren',
  'set',
  'shift',
  'start',
  'time',
  'title',
  'type',
]
const batEnvs = [
  '%ALLUSERSPROFILE%',
  '%APPDATA%',
  '%CD%',
  '%CMDCMDLINE%',
  '%CMDEXTVERSION%',
  '%CommonProgramFiles(x86)%',
  '%CommonProgramFiles%',
  '%CommonProgramW6432%',
  '%COMPUTERNAME%',
  '%ComSpec%',
  '%DATE%',
  '%DriverData%',
  '%ERRORLEVEL%',
  '%HOMEDRIVE%',
  '%HOMEPATH%',
  '%LOCALAPPDATA%',
  '%LOGONSERVER%',
  '%NUMBER_OF_PROCESSORS%',
  '%NVIDIAWHITELISTED%',
  '%OS%',
  '%PATH%',
  '%PATHEXT%',
  '%PROCESSOR_ARCHITECTURE%',
  '%PROCESSOR_IDENTIFIER%',
  '%PROCESSOR_LEVEL%',
  '%PROCESSOR_REVISION%',
  '%ProgramData%',
  '%ProgramFiles(x86)%',
  '%ProgramFiles%',
  '%ProgramW6432%',
  '%PROMPT%',
  '%PUBLIC%',
  '%RANDOM%',
  '%SESSIONNAME%',
  '%SystemDrive%',
  '%SystemRoot%',
  '%TEMP%',
  '%TIME%',
  '%TMP%',
  '%USERDOMAIN%',
  '%USERNAME%',
  '%USERPROFILE%',
  '%WINDIR%',
]

const kws = batKws.map((kw) => ({
  label: kw,
  kind: Keyword,
}))
const exes = require('./winExes.json').map(([key, val]) => ({
  label: key,
  detail: val,
  kind: Function,
}))
const combos = [
  'net computer',
  'net group',
  'net localgroup',
  'net print',
  'net session',
  'net share',
  'net start',
  'net stop',
  'net use',
  'net user',
  'net view',
].map((c) => ({ label: c, kind: Function }))
const cmds = batCmds.map((c) => ({
  label: c,
  kind: Function,
}))
const props = ['usebackq', 'delims=', 'skip=', 'tokens=', 'eol='].map((p) => ({
  label: p,
  kind: Property,
}))
const envs = batEnvs.map((e) => ({
  label: e,
  kind: Constant,
}))
const builtins = kws.concat(exes, combos, cmds, props, envs, {
  label: 'EOF',
  kind: Value,
})

fs.writeFileSync(
  'resources/batCompItems.json',
  JSON.stringify(builtins),
  'utf-8',
)
